import {
  BookOpen,
  ClipboardList,
  FileText,
  Landmark,
  LayoutDashboard,
  Receipt,
  Settings,
  Shield,
  Store,
  Truck,
  Users,
  Wallet,
} from "lucide-react";

import type { NavSection } from "@/types/navigation";

export const NAV_SECTIONS: NavSection[] = [
  {
    id: "main",
    items: [
      {
        id: "dashboard",
        labelKey: "nav.dashboard",
        href: "/dashboard",
        icon: LayoutDashboard,
        permission: "dashboard:view",
      },
      {
        id: "dealers",
        labelKey: "nav.dealers",
        href: "/dealers",
        icon: Store,
        permission: "dealers:view",
      },
      {
        id: "products",
        labelKey: "nav.products",
        href: "/products",
        icon: ClipboardList,
        permission: "products:view",
      },
      {
        id: "orders",
        labelKey: "nav.orders",
        href: "/orders",
        icon: FileText,
        permission: "orders:view",
      },
      {
        id: "delivery-challans",
        labelKey: "nav.deliveryChallans",
        href: "/delivery-challans",
        icon: Truck,
        permission: "orders:view",
      },
      {
        id: "invoices",
        labelKey: "nav.invoices",
        href: "/invoices",
        icon: Receipt,
        permission: "invoices:view",
      },
      {
        id: "collections",
        labelKey: "nav.collections",
        href: "/collections",
        icon: Wallet,
        permission: "collections:view",
      },
      {
        id: "ledger",
        labelKey: "nav.ledger",
        href: "/ledger",
        icon: BookOpen,
        permission: "ledger:view",
      },
      {
        id: "opening-balances",
        labelKey: "nav.openingBalances",
        href: "/opening-balances",
        icon: Landmark,
        permission: "invoices:create",
      },
    ],
  },
  {
    id: "admin",
    labelKey: "nav.administration",
    items: [
      {
        id: "reports",
        labelKey: "nav.reports",
        href: "/reports/due",
        icon: FileText,
        permission: "reports:view",
      },
      {
        id: "sr-performance",
        labelKey: "nav.srPerformance",
        href: "/reports/sr-performance",
        icon: FileText,
        permission: "reports:sr-performance:view",
      },
      {
        id: "product-sales-by-territory",
        labelKey: "nav.territoryProductSales",
        href: "/reports/product-sales-by-territory",
        icon: FileText,
        permission: "reports:territory-product-sales:view",
      },
      {
        id: "audit",
        labelKey: "nav.audit",
        href: "/audit",
        icon: Shield,
        permission: "audit:view",
      },
      {
        id: "users",
        labelKey: "nav.users",
        href: "/settings/users",
        icon: Users,
        permission: "users:view",
      },
      {
        id: "settings",
        labelKey: "nav.settings",
        href: "/settings",
        icon: Settings,
        permission: "settings:view",
      },
    ],
  },
];
