import ExcelJS from "exceljs";
import JSZip from "jszip";
import PDFDocument from "pdfkit";

import {
  getAuditConsoleData,
} from "../audit-service";
import type { AuditContext, AuditFilters } from "../audit-types";
import type { AuditReadClient } from "../audit-query";
import { DOC_COLORS } from "@/lib/documents/design-tokens";
import { getCompanyBranding } from "@/lib/documents/company-branding";

import { AuditExportEmptyError } from "./audit-export-errors";
import {
  buildAuditReportHtml,
  buildComplianceSummary,
  describeAppliedFilters,
  mapRecordsToExcelRows,
} from "./audit-export-mappers";
import type {
  AuditExportActor,
  AuditExportFile,
  AuditExportPayload,
} from "./audit-export-types";
import {
  assertExportWithinLimit,
  buildAuditArchiveFilename,
  buildAuditExcelFilename,
  buildAuditPdfFilename,
  normalizeExportFilters,
} from "./audit-export-validation";
import { MAX_AUDIT_EXPORT_BATCH } from "./audit-export-types";

const EXPORT_QUERY_OPTIONS = { maxPageSize: MAX_AUDIT_EXPORT_BATCH } as const;

/**
 * Single read path for all export formats — consumes {@link getAuditConsoleData} only.
 */
export async function buildAuditExportPayload(
  context: AuditContext,
  actor: AuditExportActor,
  filters: AuditFilters,
  client?: AuditReadClient,
): Promise<AuditExportPayload> {
  const exportFilters = normalizeExportFilters(filters);
  const console = await getAuditConsoleData(
    context,
    exportFilters,
    client,
    EXPORT_QUERY_OPTIONS,
  );

  assertExportWithinLimit(console.total);

  if (console.records.length === 0) {
    throw new AuditExportEmptyError();
  }

  return {
    console,
    filters: exportFilters,
    actor,
    recordCount: console.records.length,
  };
}

function bufferFromPdf(doc: InstanceType<typeof PDFDocument>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}

function formatPdfDate(iso: string): string {
  return new Date(iso).toLocaleString("en-GB", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
}

/**
 * Landscape A4 PDF using enterprise document colors.
 */
export async function generateAuditPdfBuffer(
  payload: AuditExportPayload,
): Promise<Buffer> {
  const branding = getCompanyBranding();
  const doc = new PDFDocument({
    size: "A4",
    layout: "landscape",
    margin: 36,
    bufferPages: true,
  });

  const enterpriseBlue = DOC_COLORS.enterpriseBlue;
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  doc
    .fillColor(enterpriseBlue)
    .fontSize(20)
    .text("Audit Report", { align: "left" });
  doc
    .fillColor("#64748b")
    .fontSize(10)
    .text(`${branding.companyName} — Compliance Export`, { align: "left" });
  doc.moveDown(0.5);

  doc.fillColor("#0f172a").fontSize(9);
  doc.text(`Generated At: ${formatPdfDate(payload.console.generatedAt)}`);
  doc.text(`Generated By: ${payload.actor.userName}`);
  doc.text(`Role: ${payload.actor.role}`);
  doc.text(`Record Count: ${payload.recordCount}`);
  doc.moveDown(0.5);

  doc.fillColor(enterpriseBlue).fontSize(11).text("Applied Filters");
  for (const row of describeAppliedFilters(payload.filters)) {
    doc.fillColor("#334155").fontSize(9).text(`${row.label}: ${row.value}`);
  }
  doc.moveDown(0.5);

  const { summary } = payload.console;
  doc.fillColor(enterpriseBlue).fontSize(11).text("Summary");
  doc
    .fillColor("#0f172a")
    .fontSize(9)
    .text(
      `Total: ${summary.totalEvents} | Financial: ${summary.financialEvents} | Security: ${summary.securityEvents} | Dealer: ${summary.dealerEvents} | Integrity: ${summary.integrityEvents}`,
    );
  doc.moveDown(0.5);

  doc.fillColor(enterpriseBlue).fontSize(11).text("Timeline");
  for (const group of payload.console.timeline) {
    doc.fillColor("#334155").fontSize(9).text(`${group.key} (${group.records.length})`);
    for (const record of group.records.slice(0, 8)) {
      doc
        .fillColor("#0f172a")
        .fontSize(8)
        .text(
          `• ${formatPdfDate(record.createdAt)} — ${record.action} — ${record.entityType} ${record.entityId}`,
          { width: pageWidth },
        );
    }
    if (group.records.length > 8) {
      doc.fillColor("#64748b").fontSize(8).text(`… and ${group.records.length - 8} more`);
    }
  }
  doc.moveDown(0.5);

  doc.fillColor(enterpriseBlue).fontSize(11).text("Records");
  const columns = [
    { label: "Date", width: 95 },
    { label: "Action", width: 110 },
    { label: "Entity", width: 70 },
    { label: "ID", width: 80 },
    { label: "User", width: 90 },
    { label: "Metadata", width: pageWidth - 445 },
  ];

  let y = doc.y;
  let x = doc.page.margins.left;
  doc.fontSize(8).fillColor("#f8fafc");
  doc.rect(x, y, pageWidth, 16).fill("#f1f5f9");
  doc.fillColor("#0f172a");
  for (const column of columns) {
    doc.text(column.label, x + 4, y + 4, { width: column.width - 8, lineBreak: false });
    x += column.width;
  }
  y += 18;

  for (const record of payload.console.records) {
    if (y > doc.page.height - doc.page.margins.bottom - 24) {
      doc.addPage();
      y = doc.page.margins.top;
    }
    x = doc.page.margins.left;
    const metadata = Object.entries(record.metadata)
      .map(([key, value]) => `${key}: ${String(value)}`)
      .join("; ");
    const cells = [
      formatPdfDate(record.createdAt),
      record.action,
      record.entityType,
      record.entityId,
      record.userName ?? "—",
      metadata,
    ];
    let rowHeight = 14;
    for (let index = 0; index < columns.length; index += 1) {
      const height = doc.heightOfString(cells[index] ?? "", {
        width: columns[index].width - 8,
      });
      rowHeight = Math.max(rowHeight, height + 6);
    }
    for (let index = 0; index < columns.length; index += 1) {
      doc
        .fillColor("#0f172a")
        .fontSize(7)
        .text(cells[index] ?? "", x + 4, y + 3, {
          width: columns[index].width - 8,
        });
      x += columns[index].width;
    }
    y += rowHeight;
    doc
      .strokeColor("#e2e8f0")
      .moveTo(doc.page.margins.left, y)
      .lineTo(doc.page.width - doc.page.margins.right, y)
      .stroke();
  }

  return bufferFromPdf(doc);
}

export async function generateAuditExcelBuffer(
  payload: AuditExportPayload,
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = payload.actor.userName;
  workbook.created = new Date(payload.console.generatedAt);

  const sheet = workbook.addWorksheet("Audit Records");
  sheet.columns = [
    { header: "Date", key: "date", width: 22 },
    { header: "Action", key: "action", width: 28 },
    { header: "Category", key: "category", width: 14 },
    { header: "Entity Type", key: "entityType", width: 16 },
    { header: "Entity ID", key: "entityId", width: 18 },
    { header: "User", key: "user", width: 20 },
    { header: "Role", key: "role", width: 14 },
    { header: "Territory", key: "territory", width: 18 },
    { header: "Metadata Summary", key: "metadataSummary", width: 48 },
  ];

  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: "FF1A5DAD" } };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FFF8FAFC" },
  };

  for (const row of mapRecordsToExcelRows(payload.console.records)) {
    sheet.addRow({
      ...row,
      date: formatPdfDate(row.date),
    });
  }

  sheet.views = [{ state: "frozen", ySplit: 1 }];
  const arrayBuffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(arrayBuffer);
}

export async function generateAuditArchiveBuffer(
  payload: AuditExportPayload,
): Promise<Buffer> {
  const zip = new JSZip();
  const [pdfBuffer, excelBuffer] = await Promise.all([
    generateAuditPdfBuffer(payload),
    generateAuditExcelBuffer(payload),
  ]);
  const summary = buildComplianceSummary(payload);

  zip.file("audit-report.pdf", pdfBuffer);
  zip.file("audit-records.xlsx", excelBuffer);
  zip.file("compliance-summary.json", JSON.stringify(summary, null, 2));

  return zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
}

function toBase64(buffer: Buffer): string {
  return buffer.toString("base64");
}

export async function createAuditPdfExport(
  payload: AuditExportPayload,
): Promise<AuditExportFile> {
  const buffer = await generateAuditPdfBuffer(payload);
  return {
    filename: buildAuditPdfFilename(payload.console.generatedAt),
    contentType: "application/pdf",
    data: toBase64(buffer),
    recordCount: payload.recordCount,
  };
}

export async function createAuditExcelExport(
  payload: AuditExportPayload,
): Promise<AuditExportFile> {
  const buffer = await generateAuditExcelBuffer(payload);
  return {
    filename: buildAuditExcelFilename(payload.console.generatedAt),
    contentType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    data: toBase64(buffer),
    recordCount: payload.recordCount,
  };
}

export async function createAuditArchiveExport(
  payload: AuditExportPayload,
): Promise<AuditExportFile> {
  const buffer = await generateAuditArchiveBuffer(payload);
  return {
    filename: buildAuditArchiveFilename(payload.console.generatedAt),
    contentType: "application/zip",
    data: toBase64(buffer),
    recordCount: payload.recordCount,
  };
}

/**
 * Printable HTML export — document platform compatible, server-generated.
 */
export function createAuditHtmlExport(payload: AuditExportPayload): AuditExportFile {
  const html = buildAuditReportHtml(payload);
  return {
    filename: buildAuditPdfFilename(payload.console.generatedAt).replace(
      ".pdf",
      ".html",
    ),
    contentType: "text/html; charset=utf-8",
    data: toBase64(Buffer.from(html, "utf-8")),
    recordCount: payload.recordCount,
  };
}
